language: node_js
node_js:
  - '10.9.0'

stages:
  - test
  - name: deploy

jobs:
  include:
    - stage: test
      script:
        - npm test

    - stage: deploy
      script:
        - npm run build

      deploy:
        provider: npm
        email: '$npm_email'
        api_key: '$npm_key'
        skip_cleanup: true
        on:
          tags: true